### ISSUE TITLE
Download all dependencies regardless of the scope

### ISSUE THREAD

**Issue by alexkubica** [Gemba/mvn-dd#1]
How can I modify the code to make it download all dependency whether the scope is provided, test or whatever?
I tried changing the instantiation of Dependency on class DependencyResolver to get a null instead of JavaScopes.COMPILE but it didn't seem to be working.

**Comment by Gemba** [comment]
Can't spent much time on it right now. You should be able to with these tips:

https://stackoverflow.com/questions/35119307/aether-how-to-get-dependencies-with-hierarchy

I did a version lift so the tips there should be applicable without hassle. I am more than happy if you can provide a PR.

**Comment by alexkubica** [comment]
Thanks, I modified my forked project. It seems to be working but an exception is thrown on some cases, for example if I run the command:
`java -jar mvn-dependency-downloader-jar-with-dependencies.jar -d dest org.jongo:jongo:jar:1.2`
It complains it cannot find an artifact named: stax:stax-ri:jar:1.0 which I cannot find on maven repo.
This is really werid, should I just catch the excpetion and ignore it?

**Comment by Gemba** [comment]
Since it is not in my code base I can only guess. Most likely you are missing a `RemoteRepository`.
See the constructor of `RepositorySystemHelper` in ad4dc73 to find out what i mean. 

The stax-ri is listed in http://maven.nuxeo.org/nexus/content/groups/public/  (see also https://stackoverflow.com/questions/10036984/finding-missing-maven-artifacts)
HTH

**Comment by alexkubica** [comment]
Yes, adding the remote repository did solve that problem.
I'll send you a PR soon, thank you.

**Comment by Gemba** [comment]
Closing this. Thanks for your PR 44a8962.
